tas2580_usermap_index:
    pattern: /usermap/
    defaults: { _controller: tas2580.usermap.main:index }
tas2580_usermap_position:
    pattern: /usermap/position
    defaults: { _controller: tas2580.usermap.main:position }
tas2580_usermap_search:
    pattern: /usermap/search
    defaults: { _controller: tas2580.usermap.main:search }
tas2580_usermap_search_page:
    pattern: /usermap/search/page-{start}.html
    defaults: { _controller: tas2580.usermap.main:search }