services:
    tas2580.usermap.main:
        class: tas2580\usermap\controller\main
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @pagination
            - @path_helper
            - @request
            - @ext.manager
            - @user
            - @template
            - %core.root_path%
            - %core.php_ext%
    tas2580.usermap.listener:
        class: tas2580\usermap\event\listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @path_helper
            - @ext.manager
            - @template
            - @user
        tags:
            - { name: event.listener }
    tas2580.usermap.listener_acp:
        class: tas2580\usermap\event\listener_acp
        arguments:
            - @ext.manager
            - @path_helper
            - @request
            - @user
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }
    tas2580.usermap.listener_ucp:
        class: tas2580\usermap\event\listener_ucp
        arguments:
            - @auth
            - @controller.helper
            - @request
            - @user
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }